# Unix submit description file
# kt_xNAMEfile.sub -- simple Marlin job

executable              = runddsim_QGSP_BERT_conf1_e-_1GeV_0.sh
log                     = ../log/runddsim_QGSP_BERT_conf1_e-_1GeV_0.log
output                  = ../log/outfile_runddsim_QGSP_BERT_conf1_e-_1GeV_0.txt
error                   = ../log/errors_runddsim_QGSP_BERT_conf1_e-_1GeV_0.txt
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue -short
